import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import { ClerkProvider } from "@clerk/nextjs";

import { ModalProvider } from "@/components/modal-provider";
import ToastProvider from "@/components/toast-provider";
import { CrispProvider } from "@/components/crisp-provider";
const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
   
   <ClerkProvider>
       
      <html lang="en">
      
      <body className={inter.className}>
      <ModalProvider>     
        <ToastProvider/>
        <CrispProvider/>
          {children}
          
          </ModalProvider>
        </body>
    </html>
    
   </ClerkProvider>
  
  );
}
